### ISSUE TITLE
use official, auto-generated Google API client

### ISSUE THREAD

**Issue by kaibolay** [firebase/fastlane-plugin-firebase_app_distribution#305]
This plugin should use the official, auto-generated Google API client: [google-apis-firebaseappdistribution_v1](https://github.com/googleapis/google-api-ruby-client/tree/main/generated/google-apis-firebaseappdistribution_v1) ([RubyGems](https://rubygems.org/gems/google-apis-firebaseappdistribution_v1)) instead of the hand-written [firebase_app_distribution_api_client.rb](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/master/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb).

**Comment by lfkellogg** [comment]
This was partially rolled back due to slow uploads: https://github.com/firebase/fastlane-plugin-firebase_app_distribution/pull/336
