### ISSUE TITLE
TransmissionError Android 0.8.1

### ISSUE THREAD

**Issue by gmcdowell** [firebase/fastlane-plugin-firebase_app_distribution#361]
### Issue Description
Failed to upload apk to FirebaseAppDistribution - works for iOS

##### Configuration
`
    firebase_app_distribution(
      apk_path: apk_file,
      groups: "internal",
      app: ENV['ANDROID_FIREBASE_APP_ID'],
      service_credentials_file: ENV['ANDROID_FIREBASE_APP_DISTRIBUTION_CREDENTIALS_FILE_PATH'],
      release_notes: changelog,
      debug: true
    )
`

##### Complete verbose output
`
[08:56:39]: ---------------------------------------
[08:56:39]: --- Step: firebase_app_distribution ---
[08:56:39]: ---------------------------------------
[08:56:39]: Warning: Debug logging enabled. Output may include sensitive information.
[08:56:39]: 🔐 Authenticating with --service_credentials_file path parameter: /Users/greg/Projects/logmate-flutter/android/../app-distribution-logmate-production.json
[08:56:39]: 📡 Uploading the APK.
D, [2024-02-05T08:56:39.856823 #84172] DEBUG -- : Sending HTTP post https://firebaseappdistribution.googleapis.com/upload/v1/projects/xyz/apps/1:xyz:android:xyz/releases:upload?
D, [2024-02-05T09:01:40.291218 #84172] DEBUG -- : Caught error execution expired
D, [2024-02-05T09:01:40.294110 #84172] DEBUG -- : Error - #<HTTPClient::SendTimeoutError: execution expired>

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  Lane Context                                                                                  |
+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM               | android                                                                                                                                       |
| PLATFORM_NAME                  | android                                                                                                                                       |
| LANE_NAME                      | android internal                                                                                                                              |
|
+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
[09:01:40]: execution expired

+------------------------------------------------------------------------------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | clean                                                         | 4           |
| 3    | Switch to android sh_on_root lane                             | 0           |
| 4    | cd /Users/greg/Projects/myproject-flutter && flutter analyze    | 2           |
| 5    | Switch to android sh_on_root lane                             | 0           |
| 6    | cd /Users/greg/Projects/myproject-flutter && flutter build apk  | 19          |
| 7    | read_pubspec_version                                          | 0           |
| 8    | read_changelog                                                | 0           |
| 💥   | firebase_app_distribution                                     | 300         |
+------+---------------------------------------------------------------+-------------+

[09:01:40]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane error with Android when upload aab file to firebase distribution: execution expired (Google::Apis::TransmissionError)
    https://github.com/fastlane/fastlane/issues/21438 [open] 7 💬
    2 weeks ago

➡️  fastlane supply --aab path/xxx.aab error
    https://github.com/fastlane/fastlane/issues/21335 [open] 6 💬
    20 Sep 2023

➡️   Failed to open TCP connection to www.googleapis.com:443 
    https://github.com/fastlane/fastlane/issues/21698 [open] 0 💬
    06 Dec 2023

and 58 more at: https://github.com/fastlane/fastlane/search?q=execution%20expired&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/greg/.rbenv/versions/3.2.3/bin/fastlane)
/Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:354:in `syswrite': [!] execution expired (Google::Apis::TransmissionError)
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:354:in `do_write'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:371:in `block in write'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:370:in `each'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:370:in `inject'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:370:in `write'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:582:in `dump_file'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:508:in `dump'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/timeout.rb:196:in `timeout'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:318:in `execute_once'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:131:in `block (2 levels) in do_retry'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:128:in `block in do_retry'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:118:in `do_retry'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:109:in `execute'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:418:in `execute_or_queue_command'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:265:in `http'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-plugin-firebase_app_distribution-0.8.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:264:in `upload_binary'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-plugin-firebase_app_distribution-0.8.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:55:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:56:in `block (2 levels) in parsing_binding'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/bin/fastlane:25:in `load'
        from /Users/greg/.rbenv/versions/3.2.3/bin/fastlane:25:in `<top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
        from /Users/greg/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
/Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:354:in `syswrite': execution expired (HTTPClient::SendTimeoutError)
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:354:in `do_write'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:371:in `block in write'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:370:in `each'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:370:in `inject'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:370:in `write'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:582:in `dump_file'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:508:in `dump'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/3.2.0/timeout.rb:196:in `timeout'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:318:in `execute_once'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:131:in `block (2 levels) in do_retry'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:128:in `block in do_retry'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:118:in `do_retry'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:109:in `execute'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:418:in `execute_or_queue_command'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:265:in `http'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-plugin-firebase_app_distribution-0.8.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:264:in `upload_binary'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-plugin-firebase_app_distribution-0.8.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:55:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:56:in `block (2 levels) in parsing_binding'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/bin/fastlane:25:in `load'
        from /Users/greg/.rbenv/versions/3.2.3/bin/fastlane:25:in `<top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/greg/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
        from /Users/greg/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
        from /Users/greg/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
`

##### Environment

| Library     | Version |
| ----------- | ----------- |
| fastlane | [2.219.0] |
| fastlane-plugin-firebase_app_distribution | [0.8.1] |

**Comment by gmcdowell** [comment]
I have just downgraded to 0.7.2 and it works fine.

**Comment by kaibolay** [comment]
> Failed to upload apk to FirebaseAppDistribution - works for iOS

That's very odd. APKs and IPAs are uploaded exactly the same way. Is there a significant difference in the file size?

> I have just downgraded to 0.7.2 and it works fine.

How long does the upload (specifically the `POST` to the upload URL) take with that version? 

Maybe the APK upload takes close to 5 minutes (300 seconds - which is the default timeout) and the upload with the new version is slightly slower. Try specifying a longer `upload_timeout`.

**Comment by gmcdowell** [comment]
Looks like setting the `upload_timeout` did the trick.

thx eh
