### ISSUE TITLE
Conflict between Fastlane and Firebase App Distribution

### ISSUE THREAD

**Issue by only2433** [firebase/fastlane-plugin-firebase_app_distribution#370]
### *** Steps to file a bug ***
1. Try updating to the latest version of [this plugin](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases), and [fastlane](https://github.com/fastlane/fastlane/releases)
2. If the issue persists, fill out the sections below
3. Delete this section and submit

### Issue Description
[11:21:08]: 59: end
[11:21:08]: 60: end
[11:21:08]: => 61: xczvxzcvl;kjb `````` ``

[!] Syntax error in your Fastfile on line 61: Fastfile:61: syntax error, unexpected backtick literal, expecting end-of-input
xczvxzcvl;kjb

##### Configuration
  desc "Lane for distribution"
      lane :distribute do
          gradle(
              task: "assemble",
              build_type: "Release",
              properties: {
                  "android.injected.signing.store.file" => ENV['SIGNED_STORE_FILE'],
                  "android.injected.signing.store.password" => ENV['SIGNED_STORE_PASSWORD'],
                  "android.injected.signing.key.alias" => ENV['SIGNED_KET_ALIAS'],
                  "android.injected.signing.key.password" => ENV['SIGNED_KEY_PASSWORD']
              }
          )

          firebase_app_distribution(
              app: ENV['APP_ID'],
              groups: "developer",
              release_notes: "[수정사항]\n -  UserAgent 삭제 (심사 전 테스트)",
              debug: true,
              firebase_cli_token: ENV['FIREBASE_TOKEN']
          )
      end

##### Environment
Window
Fastlane :  2.220.0
Firebase app distribution : 0.9.1
Android Studio Jellyfish | 2023.3.1

-> It works well with Fastlane 2.214.0 and Firebase App Distribution 0.7.1.

| Library     | Version |
| ----------- | ----------- |
| fastlane | [2.220.0] |
| fastlane-plugin-firebase_app_distribution | [0.9.1] |

**Comment by kaibolay** [comment]
Hi @only2433 !

> [11:21:08]: => 61: xczvxzcvl;kjb `````` ``

Any idea where this is coming from? Supposedly it's from line 61 of your `Fastfile`. Is it possible, that that file was somehow corrupted?

The issue seems unrelated to the update of `fastlane` itself or the `fastlane-plugin-firebase_app_distribution`.
