### ISSUE TITLE
iOS Distribution: firebase_app_distribution  Couldn't find binary

### ISSUE THREAD

**Issue by SaravanaB-TEL22** [firebase/fastlane-plugin-firebase_app_distribution#371]
Issue Description

Cannot run firebase_app_distribution, the script just ends with a Couldn't find binary error

**fastlane finished with errors
[!] Couldn't find binary**

Command executed
firebase_app_distribution

Complete output when running fastlane, including the stack trace and command used -->

Complete verbose output

DEBUG [2024-07-06 02:10:34.41]: All plugins are up to date
ERROR [2024-07-06 02:10:34.41]: fastlane finished with errors
DEBUG [2024-07-06 02:10:34.41]: All plugins are up to date
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Couldn't find binary. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:37:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:97:in `block (2 levels) in parsing_binding'
	from Fastfile:82:in `each'
	from Fastfile:82:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Couldn't find binary. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:37:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:97:in `block (2 levels) in parsing_binding'
	from Fastfile:82:in `each'
	from Fastfile:82:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.221.1/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>' 

On the Fastfile I've implemented two different lanes, one for the build and one for the distribution:

        export_methods.each { |export_method|
        gym(
          archive_path: archive_path,
          skip_build_archive: true,
          output_name: "xxx.ipa",
          export_method: export_method,
          build_path: ".../builds",
          output_directory: ".../builds",
          scheme: scheme,
          xcargs: '-allowProvisioningUpdates -disableAutomaticPackageResolution' + authentication_key,
          skip_package_dependencies_resolution: true
         )

        case export_method
        when "ad-hoc", "development"
          firebase_app_distribution(
            # Fix Tester groups
            # Could not enable access for testers.
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            app: ENV['FIREBASE_APP_ID'],
            groups: ENV['FIREBASE_TESTER_GROUP'],
            release_notes: release_notes,
            ipa_path: ".../builds/xxx.ipa",
            debug: true
          )
        when "app-store"
          pilot(
            api_key: api_key,
            skip_submission: true,
            skip_waiting_for_build_processing: true
          )
        else
          UI.message "unknonw export method #{export_method}, not uploading"
        end
      }

**Comment by tejasd** [comment]
Hi @SaravanaB-TEL22 

I'm not sure it's possible to debug/reproduce this issue based on the provided information.

Can you try reproducing this with the following steps:
1. Comment out the `gym`.
2. Manually generate the .ipa, and place it in the location specified in the `ipa_path` parameter of `firebase_app_distribution`.
3. Run your lanes again, with the manually generated `.ipa`.

Post the logs/result of that.

Thanks!

**Comment by tagboola** [comment]
Feel free to re-open the issue if necessary.
