### ISSUE TITLE
Use google Service API key

### ISSUE THREAD

**Issue by ced455** [firebase/fastlane-plugin-firebase_app_distribution#372]
Hi, I don't know if it's just undocumented or not yet available so feel free to close the ticket if i missed something.

In the official doc [here ](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane?hl=en)
 in [Use Firebase service account credentials](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane?hl=en#service-acc-fastlane) step 4 i have this message : 

> Skip this step if you created your app after September 20, 2019: In the Google APIs console, enable the [Firebase App Distribution API.](https://console.developers.google.com/apis/api/firebaseappdistribution.googleapis.com/overview?project=_) When prompted, select the project with the same name as your Firebase project.

I have now an API key but no step in the doc how to use it since now it's not a .json file.

Could you point me in the right direction ? Should I keep using the json file ?

Thanks,

**Comment by kaibolay** [comment]
Yes, you should use the JSON file which you created in this step:

> 3. Create a private json key and move the key to a location accessible to your build environment. Be sure to keep this file somewhere safe, as it grants administrator access to App Distribution in your Firebase project.
