### ISSUE TITLE
Execution expired for get_latest_release

### ISSUE THREAD

**Issue by angelica-snowit** [firebase/fastlane-plugin-firebase_app_distribution#375]
### Issue Description
In these latest months, the "Execution expired" error appears almost once out of two for action firebase_app_distribution_get_latest_release.

##### Configuration
```
firebase_app_distribution_get_latest_release(
    service_credentials_file: "../service-credentials.json",
    app: "1:xxxxxxxx:ios:xxxxxxxx"
)
```

##### Environment

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.225.0 |
| fastlane-plugin-firebase_app_distribution | 0.9.1 |

**Comment by kaibolay** [comment]
Please elaborate. Could you supply any more details  (including the output in `--verbose` mode) about the "Execution expired" error?

**Comment by kaibolay** [comment]
The error message most likely comes from the [`timeout` method](https://github.com/ruby/timeout/blob/ad9bf8bb07ee48e2cc04abec5fbc5678cd2f7546/lib/timeout.rb#L171), which is used by [`httpclient`](https://github.com/search?q=repo%3Anahi%2Fhttpclient+timeout%28&type=code) which in turn is used by the Google API client libraries.

The default `send_timeout` is 120 seconds and the default `receive_timeout` is 60 seconds.

Is it possible that your network connection is so slow that it takes more than a minute to receive a response?

Or maybe the server is very slow. Do you have an unusually large number of releases?

**Comment by angelica-snowit** [comment]
Sadly, obtaining the logs in debug mode it's difficult: when I release and it fails, the second retry (with the debug option) usually is ok. My connection is not slow and I have at maximun 5 releases.

**Comment by kaibolay** [comment]
Maybe you can try to run `firebase_app_distribution_get_latest_release` in isolation? It should be possible to run that repeatedly without any unwanted side-effects.

**Comment by tagboola** [comment]
Closing for now. Please reopen if you have logs and need more help.
