### ISSUE TITLE
[error] Error loading plugin 'fastlane-plugin-firebase_app_distribution': Unable to activate google-apis-firebaseappdistribution_v1-0.3.0, because google-apis-core-0.3.0 conflicts with google-apis-core (>= 0.11.0, < 2.a)

### ISSUE THREAD

**Issue by Fangh** [firebase/fastlane-plugin-firebase_app_distribution#380]
### Issue Description
When using it on Unity Cloud Build I have this issue :
> [error] Error loading plugin 'fastlane-plugin-firebase_app_distribution': Unable to activate google-apis-firebaseappdistribution_v1-0.3.0, because google-apis-core-0.3.0 conflicts with google-apis-core (>= 0.11.0, < 2.a)

##### Configuration
```
  lane :ios_dev_app_distribution do #lane Firebase App Distribution
    desc "Pushing iOS build to Firebase App Distribution"
    firebase_app_distribution(
        app: ENV['FIREBASE_APP'],
        service_credentials_file: ENV['GOOGLE_APPLICATION_CREDENTIALS'],
        ipa_path: ENV['UNITY_PLAYER'],
        release_notes_file: ENV['RELEASE_NOTES_PATH'],
        groups: ENV['FIREBASE_GROUPS'],
        debug: ENV['FIREBASE_DEBUG_OUTPUT']
    )
  end
```

##### Complete verbose output
You can find it attached

##### Environment
Look at my gemfile.lock

| Library     | Version |
| ----------- | ----------- |
| fastlane | [2.223.1] |
| fastlane-plugin-firebase_app_distribution | [0.9.1] |

[error.log](https://github.com/user-attachments/files/18061930/error.log)
[Gemfile.zip](https://github.com/user-attachments/files/18061947/Gemfile.zip)

**Comment by kaibolay** [comment]
Looking at the `error.log` and `Gemfile.lock` I see that `google-apis-core` was eventually successfully updated to 0.11.3. The  `firebase_app_distribution` plugin the worked fine (see the end of the attached `error.log`):

```
---------------------------------------
--- Step: firebase_app_distribution ---
---------------------------------------
📡 Uploading the IPA.
🕵️ Validating upload…
✅ Uploaded IPA successfully and created release 00.07.15 (000715).
⏩ No release notes passed in. Skipping this step.
📦 Distributing release.
🎉 App Distribution upload finished successfully. Setting Actions.lane_context[SharedValues::FIREBASE_APP_DISTRO_RELEASE] to the uploaded release.
+------------------------------------------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | firebase_app_distribution | 16          |
+------+---------------------------+-------------+
fastlane.tools finished successfully 🎉
```
